import React, { useState, useEffect } from 'react';
import { FaSave, FaTimes, FaCalculator, FaPrint } from 'react-icons/fa';

export default function BagPurchaseForm({ purchase, suppliers, onClose, onSave }) {
  const [formData, setFormData] = useState({
    purchaseNumber: 'Auto-generated',
    supplier: '',
    productType: '',
    quantity: 0,
    unit: '',
    unitPrice: 0,
    totalPrice: 0,
    purchaseDate: new Date().toISOString().split('T')[0],
    status: 'Pending',
    paymentStatus: 'Pending',
    paidAmount: 0,
    remainingAmount: 0,
    warehouse: '',
    notes: '',
    receivingGatePass: false
  });

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [inventoryItems, setInventoryItems] = useState([]);
  const [warehouses, setWarehouses] = useState([]);
  const [inventoryLoading, setInventoryLoading] = useState(false);
  const [warehousesLoading, setWarehousesLoading] = useState(false);

  const isEditing = !!purchase;

  // Fetch inventory items
  useEffect(() => {
    const fetchInventoryItems = async () => {
      setInventoryLoading(true);
      try {
        const response = await fetch('/api/inventory');
        if (response.ok) {
          const data = await response.json();
          setInventoryItems(data.data || []);
        }
      } catch (error) {
        console.error('Error fetching inventory items:', error);
      } finally {
        setInventoryLoading(false);
      }
    };

    fetchInventoryItems();
  }, []);

  // Fetch warehouses
  useEffect(() => {
    const fetchWarehouses = async () => {
      setWarehousesLoading(true);
      try {
        const response = await fetch('/api/warehouses');
        if (response.ok) {
          const data = await response.json();
          setWarehouses(data.data || []);
        }
      } catch (error) {
        console.error('Error fetching warehouses:', error);
      } finally {
        setWarehousesLoading(false);
      }
    };

    fetchWarehouses();
  }, []);

  useEffect(() => {
    if (purchase) {
      setFormData({
        purchaseNumber: purchase.purchaseNumber || '',
        supplier: purchase.supplier ? (purchase.supplier._id || purchase.supplier) : '',
        productType: purchase.productType || '',
        quantity: purchase.quantity || 0,
        unit: purchase.unit || '',
        unitPrice: purchase.unitPrice || 0,
        totalPrice: purchase.totalPrice || 0,
        purchaseDate: new Date(purchase.purchaseDate).toISOString().split('T')[0],
        status: purchase.status || 'Pending',
        paymentStatus: purchase.paymentStatus || 'Pending',
        paidAmount: purchase.paidAmount || 0,
        remainingAmount: purchase.remainingAmount || 0,
        warehouse: purchase.warehouse || '',
        notes: purchase.notes || '',
        receivingGatePass: purchase.receivingGatePass || false
      });
    } else {
      // Purchase number will be auto-generated by the backend
      setFormData(prev => ({
        ...prev,
        purchaseNumber: 'Auto-generated'
      }));
    }
  }, [purchase]);

  const handleInputChange = (e) => {
    const { name, value, type, checked } = e.target;
    const newFormData = {
      ...formData,
      [name]: type === 'checkbox' ? checked : value
    };
    
    // Calculate total price when quantity or unit price changes
    if (name === 'quantity' || name === 'unitPrice') {
      const quantity = name === 'quantity' ? parseFloat(value) || 0 : formData.quantity;
      const unitPrice = name === 'unitPrice' ? parseFloat(value) || 0 : formData.unitPrice;
      newFormData.totalPrice = quantity * unitPrice;
    }

    // Update unit when product type changes
    if (name === 'productType') {
      const selectedItem = inventoryItems.find(item => item.name === value);
      if (selectedItem) {
        // Set unit based on inventory item weight
        const weight = selectedItem.weight;
        if (weight >= 1000) {
          newFormData.unit = `${weight/1000}kg bags`;
        } else if (weight >= 100) {
          newFormData.unit = `${weight}kg bags`;
        } else {
          newFormData.unit = `${weight}kg bags`;
        }
      }
    }

    // Calculate remaining amount when paid amount changes
    if (name === 'paidAmount') {
      const paidAmount = parseFloat(value) || 0;
      const totalPrice = newFormData.totalPrice || formData.totalPrice;
      newFormData.remainingAmount = totalPrice - paidAmount;
    }

    // Update remaining amount when total price changes
    if (name === 'quantity' || name === 'unitPrice') {
      const paidAmount = parseFloat(formData.paidAmount) || 0;
      const totalPrice = newFormData.totalPrice;
      newFormData.remainingAmount = totalPrice - paidAmount;
    }
    
    setFormData(newFormData);
  };


  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError(null);

    console.log('Form submitted with data:', formData);

    try {
      await onSave(formData);
      onClose();
    } catch (err) {
      console.error('Form submission error:', err);
      setError(err.message || 'Failed to save purchase');
    } finally {
      setLoading(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  // Filter suppliers to show only private suppliers
  const privateSuppliers = suppliers.filter(supplier => supplier.supplierType === 'Private');

  // Handle different action buttons
  const handlePrintInvoice = () => {
    window.print();
  };

  const handleSaveInvoice = async () => {
    await handleSubmit();
  };

  const handlePrintAndSave = async () => {
    await handleSubmit();
    setTimeout(() => {
      window.print();
    }, 1000);
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white rounded-lg p-6 w-full max-w-4xl max-h-[90vh] overflow-y-auto">
        <div className="flex justify-between items-center mb-6">
          <h2 className="text-2xl font-bold text-gray-900">
            {isEditing ? 'Edit Bag Purchase' : 'New Bag Purchase'}
          </h2>
          <div className="flex space-x-2">
            <button
              type="button"
              onClick={handlePrint}
              className="bg-gray-600 text-white px-4 py-2 rounded-lg hover:bg-gray-700 transition-colors flex items-center"
            >
              <FaPrint className="mr-2" />
              Print
            </button>
            <button
              type="button"
              onClick={onClose}
              className="bg-red-600 text-white px-4 py-2 rounded-lg hover:bg-red-700 transition-colors flex items-center"
            >
              <FaTimes className="mr-2" />
              Close
            </button>
          </div>
        </div>

        {error && (
          <div className="bg-red-50 border border-red-200 rounded-md p-4 mb-6">
            <div className="text-red-600">Error: {error}</div>
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-6">
          {/* Basic Information */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Purchase Number
              </label>
              <input
                type="text"
                name="purchaseNumber"
                value={formData.purchaseNumber}
                readOnly
                className="w-full px-3 py-2 border border-gray-300 rounded-md bg-gray-100 text-gray-600 cursor-not-allowed"
                placeholder="Auto-generated by system"
              />
              <p className="mt-1 text-xs text-gray-500">Purchase number will be generated automatically</p>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Supplier * (Private Only)
              </label>
              <select
                name="supplier"
                value={formData.supplier}
                onChange={handleInputChange}
                required
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              >
                <option value="">Select private supplier</option>
                {privateSuppliers.map((s) => (
                  <option key={s._id} value={s._id}>
                    {s.name} ({s.supplierCode})
                  </option>
                ))}
              </select>
              <p className="mt-1 text-xs text-gray-500">Only private suppliers are shown for bag purchases</p>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Product Type * (From Inventory)
              </label>
              <select
                name="productType"
                value={formData.productType}
                onChange={handleInputChange}
                required
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                disabled={inventoryLoading}
              >
                <option value="">Select product from inventory</option>
                {inventoryItems.map((item) => (
                  <option key={item._id} value={item.name}>
                    {item.name} ({item.weight}kg)
                  </option>
                ))}
              </select>
              {inventoryLoading && (
                <p className="mt-1 text-xs text-gray-500">Loading inventory items...</p>
              )}
              <p className="mt-1 text-xs text-gray-500">Select from your saved inventory items</p>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Quantity *
              </label>
              <input
                type="number"
                name="quantity"
                value={formData.quantity}
                onChange={handleInputChange}
                required
                min="0"
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Unit * (From Inventory)
              </label>
              <input
                type="text"
                name="unit"
                value={formData.unit}
                readOnly
                className="w-full px-3 py-2 border border-gray-300 rounded-md bg-gray-100 text-gray-600 cursor-not-allowed"
                placeholder="Unit will be set based on selected product"
              />
              <p className="mt-1 text-xs text-gray-500">Unit is automatically set based on inventory item weight</p>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Unit Price *
              </label>
              <input
                type="number"
                name="unitPrice"
                value={formData.unitPrice}
                onChange={handleInputChange}
                required
                min="0"
                step="0.01"
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Total Price
              </label>
              <input
                type="number"
                value={formData.totalPrice.toFixed(2)}
                readOnly
                className="w-full px-3 py-2 border border-gray-300 rounded-md bg-gray-50 font-semibold"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Purchase Date *
              </label>
              <input
                type="date"
                name="purchaseDate"
                value={formData.purchaseDate}
                onChange={handleInputChange}
                required
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Status
              </label>
              <select
                name="status"
                value={formData.status}
                onChange={handleInputChange}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              >
                <option value="Pending">Pending</option>
                <option value="Received">Received</option>
                <option value="Completed">Completed</option>
                <option value="Cancelled">Cancelled</option>
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Payment Status
              </label>
              <select
                name="paymentStatus"
                value={formData.paymentStatus}
                onChange={handleInputChange}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              >
                <option value="Pending">Pending</option>
                <option value="Partial">Partial</option>
                <option value="Completed">Completed</option>
              </select>
            </div>
          </div>

          {/* Partial Payment Section */}
          {formData.paymentStatus === 'Partial' && (
            <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
              <h3 className="text-lg font-medium text-yellow-800 mb-4">Payment Details</h3>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Paid Amount *
                  </label>
                  <input
                    type="number"
                    name="paidAmount"
                    value={formData.paidAmount}
                    onChange={handleInputChange}
                    required
                    min="0"
                    step="0.01"
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="Enter paid amount"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Total Amount
                  </label>
                  <input
                    type="number"
                    value={formData.totalPrice.toFixed(2)}
                    readOnly
                    className="w-full px-3 py-2 border border-gray-300 rounded-md bg-gray-50 font-semibold"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Remaining Amount
                  </label>
                  <input
                    type="number"
                    value={formData.remainingAmount.toFixed(2)}
                    readOnly
                    className={`w-full px-3 py-2 border border-gray-300 rounded-md font-semibold ${
                      formData.remainingAmount > 0 ? 'bg-red-50 text-red-600' : 'bg-green-50 text-green-600'
                    }`}
                  />
                </div>
              </div>
            </div>
          )}

          {/* Warehouse Selection */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Warehouse *
            </label>
            <select
              name="warehouse"
              value={formData.warehouse}
              onChange={handleInputChange}
              required
              className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              disabled={warehousesLoading}
            >
              <option value="">Select warehouse</option>
              {warehouses.map((warehouse) => (
                <option key={warehouse._id} value={warehouse._id}>
                  {warehouse.name} - {warehouse.location}
                </option>
              ))}
            </select>
            {warehousesLoading && (
              <p className="mt-1 text-xs text-gray-500">Loading warehouses...</p>
            )}
          </div>

          {/* Receiving Gate Pass Option */}
          <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
            <div className="flex items-center">
              <input
                type="checkbox"
                name="receivingGatePass"
                checked={formData.receivingGatePass}
                onChange={handleInputChange}
                className="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded"
              />
              <label className="ml-2 block text-sm font-medium text-blue-800">
                Generate Receiving Gate Pass
              </label>
            </div>
            <p className="mt-1 text-xs text-blue-600">
              Check this box to generate a gate pass for receiving the goods
            </p>
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Notes
            </label>
            <textarea
              name="notes"
              value={formData.notes}
              onChange={handleInputChange}
              rows="3"
              className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              placeholder="Additional notes about this purchase..."
            />
          </div>

          {/* Form Actions */}
          <div className="flex justify-between items-center pt-6 border-t">
            <div className="flex space-x-3">
              <button
                type="button"
                onClick={handlePrintInvoice}
                className="bg-gray-600 text-white px-4 py-2 rounded-md hover:bg-gray-700 transition-colors flex items-center"
              >
                <FaPrint className="mr-2" />
                Print Invoice
              </button>
              <button
                type="button"
                onClick={handleSaveInvoice}
                disabled={loading}
                className="bg-green-600 text-white px-4 py-2 rounded-md hover:bg-green-700 transition-colors flex items-center disabled:opacity-50"
              >
                <FaSave className="mr-2" />
                Save Invoice
              </button>
              <button
                type="button"
                onClick={handlePrintAndSave}
                disabled={loading}
                className="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700 transition-colors flex items-center disabled:opacity-50"
              >
                <FaPrint className="mr-2" />
                Print & Save
              </button>
            </div>
            <div className="flex space-x-3">
              <button
                type="button"
                onClick={onClose}
                className="px-6 py-2 border border-gray-300 rounded-md text-gray-700 hover:bg-gray-50 transition-colors"
              >
                Cancel
              </button>
              <button
                type="submit"
                disabled={loading}
                className="bg-blue-600 text-white px-6 py-2 rounded-md hover:bg-blue-700 transition-colors flex items-center disabled:opacity-50"
              >
                <FaSave className="mr-2" />
                {loading ? 'Saving...' : (isEditing ? 'Update Purchase' : 'Create Purchase')}
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  );
} 